### ISSUE TITLE
Rendering SLS failed on file ambari.agent.service

### ISSUE THREAD

**Issue by balloontin** [glinmac/ambari-formula#1]
I am new to salt formula. When I run `salt '*' state.highstate test=TRUE`,
the error message, `Rendering SLS 'base:ambari.agent.service' failed: mapping values are not allowed here; line 13` is received.

I suspect the problem locates at line 13 in file ambari.agent.service
`- file: ambari-agent-{{ambari.version}}-config:`   the last colon should not be there.

Please correct me if I was wrong. Thanks

**Comment by glinmac** [comment]
Thanks, that sounds about right.
